### PR TITLE
Flow types improvements

### PR DESCRIPTION
**Pull request by TrySound**

### CODE REVIEW

**Comment by ds300** [comment]
Thanks again!

**Comment by TrySound** [comment]
;)

**Comment by ds300** [comment]
@TrySound I'm just going to give you push rights. I'd appreciate it if you keep making PRs so I can follow what you're doing, but you can merge them yourself. Really appreciate all the work you're doing :)

**Comment by TrySound** [comment]
Cool. Thanks to you for this project.

**Comment by TrySound** [comment]
Btw, @ds300, can you publish beta 1?

**Comment by ds300** [comment]
Sure.

**Comment by ds300** [comment]
Do you use npm or yarn? I want to make a lockfile.

**Comment by TrySound** [comment]
I like yarn. It has upgrade-interactive and lockfile merge features.

**Comment by ds300** [comment]
Ok I'm going to add `np` for doing publishing and create a yarn.lock. Also I'm going to restrict the linting to the `src` folder because it errors for >es5 features and you're using some >es5 features in the tests.

**Comment by TrySound** [comment]
There is eslint config in test, which extends root config.

**Comment by ds300** [comment]
oh. Well it was failing for me. We can sort it out later

**Comment by ds300** [comment]
image

**Comment by TrySound** [comment]
Thanks!

**Pull request merged**
