### PR TITLE
More precise flow typings

### PR DESCRIPTION
**Pull request by andreypopp**
Some updates related to recently added flow features.

### CODE REVIEW

**Comment by andreypopp** [comment]
Hm.. should CI try to build this?

**Comment by ds300** [comment]
LGTM :+1:

**Comment by ds300** [comment]
also published `derivable@beta11`

**Comment by andreypopp** [comment]
Btw. if you publish beta it would make sense to publish all beta version for a single release (`1.0.0-beta.1`, `1.0.0-beta.2`, ...) under a single tag `1.0.0-beta` so consumer packages don't need to bump each time change happens (they still pin to specific version if needed though).

Not really important or critical, just sharing my experiences with npm.

**Pull request merged**
