### PR TITLE
Remove browser section

### PR DESCRIPTION
**Pull request by TrySound**

### CODE REVIEW

**Comment by TrySound** [comment]
@ds300 Would be great to release beta.2 (or 3-beta.0 if you'd like)

**Comment by TrySound** [comment]
@ds300 Friendly ping :)

**Comment by ds300** [comment]
Oh damn, missed this. Apologies. Not near my laptop right now but will set
a reminder for tomorrow morning.

In future you can ping me on twitter about releases. I'm much more likely
to see twitter push notifications than github emails.

**Comment by TrySound** [comment]
Sure. Thanks.

**Comment by ds300** [comment]
image

**Comment by TrySound** [comment]
Thanks!

**Pull request merged**
