### PR TITLE
Renamed Lens to Proxy

### PR DESCRIPTION
**Pull request by oskbor**
Renamed Lens to Proxy as discussed in #60 and in the backlog.

**Remaining**
- [x] How do I regenerate index.html?
- [x] Can d.ts and .flow be generated from the edn file? They were updated manually in this PR.
- [x] Should the CHANGELOG be updated?
- [x] I renamed isLensed to isProxied; but is isProxy not a better name?

### CODE REVIEW

**Comment by oskbor** [comment]
I license my contributions to the DerivableJS project under the Apache License 2.0.

**Comment by ds300** [comment]
The Flow file has always been updated manually, but I used to do the index.html and .d.ts file with a tool I wrote in ClojureScript, but I removed it at some point because of bit rot. I was planning to get rid of the .edn file and the index.html, and keep some markdown-based docs updated manually somewhere, and then I suppose I'd have to update the .d.ts manually too.

The changelog should be updated, yes.

Yeah I think `isProxy` is a better name :+1:

**Comment by oskbor** [comment]
Should I get rid of the `.edn`file and `index.html` as part of this PR or should I just leave them?
Will update the PR once I have my `derivation -> derive` branch back in working order :+1:

**Comment by ds300** [comment]
It is fine to get rid of them here. I should have done it already, actually.

**Pull request merged**
